window.SITE_COPY = {
  en: {
    dir: "ltr",
    nav: ["About", "Services", "Results", "Contact"],
    cta: "Let's talk",
    hero: {
      eyebrow: "ESTRATIJIYA",
      title: "Once the strategy is built, we walk every step with you through supervision and execution.",
      tagline: "Your growth. Our system.",
      primary: "Let's talk",
      secondary: "See How We Work",
      stats: [
        { prefix: "+", value: "40", label: "Active clients" },
        { value: "7", label: "Integrated divisions" },
        { value: "Dubai", label: "Office 501" },
      ],
    },
    about: {
      n: "01", eyebrow: "What sets us apart",
      titleA: "Growth is no accident.", titleB: "It's strategy.",
      lead: "We don't sell scattered services.",
      body: "We study your company and build it from the inside out — operations, sales, marketing, and technology — into one system. Everything connected, everything measurable, and everything still working long after our part is done.",
    },
    vision: {
      n: "02", eyebrow: "Our vision",
      title: "Every path has its steps, and at the end of each step a point of success.",
      body: "We believe growth never comes by chance. Behind every jump in the numbers is a deliberate strategy and a team watching over every detail.",
    },
    method: {
      n: "03", eyebrow: "The method",
      kicker: "We draw you the map closest to your goal.",
      title: "We study. We build the strategy. Then we execute.",
      hint: "Tap any step to read the detail",
      steps: [
        { i: "01", t: "Discovery & Analysis", d: "We understand your current position, competitors, gaps, and strengths." },
        { i: "02", t: "Setting goals", d: "Strategic, measurable goals within a clear timeframe." },
        { i: "03", t: "Building the strategy", d: "A roadmap split into phases with precise ownership." },
        { i: "04", t: "Building the system", d: "We turn the strategy into operating systems the company runs on." },
        { i: "05", t: "Execution & follow-up", d: "From plan to reality — we track and adjust continuously." },
        { i: "06", t: "Review & development", d: "We review results and evolve the plans based on the data." },
      ],
    },
    services: {
      n: "04", eyebrow: "Our services",
      title: "Seven services. One system.",
      lede: "Not a menu to pick from — one integrated journey. When you work with us, we move through every phase together, not one service at a time.",
      items: [
        { t: "Studies & Strategy", d: "Set the foundation. We study your reality, define the goal, and design the strategy that gets you there." },
        { t: "Branding", d: "Become recognized. We build the visual identity that makes you the first name your customers remember." },
        { t: "Building the System", d: "Make it last. We build the operating systems, SOPs, and structure that keep the company running long after we leave." },
        { t: "Supervision & Execution", d: "Turn the plan into reality. We supervise the team, manage hiring, and align operations so the strategy actually happens." },
        { t: "IT & AI", d: "Save time, remove errors. Automate processes, build custom systems, and bring AI into the parts of your operation that need it most." },
        { t: "Marketing & Sales", d: "Fill the funnel. We bring in customers, build the sales journey, and close more deals." },
      ],
      featured: { eyebrow: "A foundation of success", t: "Personal Branding", d: "The founder is the first impression. We turn your visibility into a long-term commercial asset — opening doors to partnerships, talent, and the customers you actually want." },
    },
    audience: {
      n: "05", eyebrow: "Who we work with",
      title: "Start the right way.",
      lede: "Whether you're launching something new or scaling an existing company — we set the right foundation from day one.",
      a: {
        tag: "Highest impact",
        t: "If you're starting a new venture",
        d: "Begin on solid ground before mistakes set in. A clear strategy, an operating system from day one, a personal and commercial brand, and a team that knows where it's headed.",
        items: ["Feasibility study and a detailed business plan", "Operating structure and SOPs before your first client", "A consistent commercial and personal brand", "Full supervision through the first 6 months"],
      },
      b: {
        t: "If you already run a company",
        d: "We analyze what works and what doesn't, reset priorities, and build a phased development plan. We work with your reality in full detail — not idealized assumptions.",
        items: ["Mapping the gaps in your current systems", "Restructuring sales and marketing", "Developing leadership and the team", "A growth plan backed by numbers"],
      },
    },
    results: {
      n: "06", eyebrow: "The real work",
      title: "What we actually deliver",
      lede: "In our work with a single client, here's what we delivered:",
      items: [
        { i: "01", t: "We built the company's foundation", d: "We started by understanding the reality, then set the strategy, then implemented work systems that outlast us." },
        { i: "02", t: "Five full hiring stages", d: "From job description to final offer — we planned and managed hiring for 15+ roles." },
        { i: "03", t: "Full client-management automation", d: "We connected the systems, set up HubSpot and Zoho, and automated follow-up from first meeting to closed deal." },
        { i: "04", t: "Decisions grounded in numbers", d: "Supplier comparisons, technical-spec analysis, financial models, and investment documents." },
        { i: "05", t: "A sales funnel from zero", d: "We built the sales channels and designed the customer journey from first contact to signed deal." },
        { i: "06", t: "Identity, campaigns, and content", d: "From visual identity to Google and Meta campaigns, plus monthly content management." },
      ],
      close: "And all of this… with one company. At one time.",
    },
    partners: { n: "07", title: "Partners in success", lede: "Brands that trusted their growth with us", close: "With you from the first idea… to the first client… to the first expansion." },
    contact: {
      n: "08", title: "Your first step toward growth.",
      body: "The first consultation is always free. Because understanding before execution isn't optional — it's our foundation.",
      primary: "Let's talk", secondary: "Message us on WhatsApp ↗",
    },
    footer: { tagline: "Your growth. Our system.", address: "Office 501, Dubai, UAE", links: "Quick links", touch: "Get in touch", rights: "© 2025 Estratijiya. All rights reserved." },
  },
  ar: {
    dir: "rtl",
    nav: ["من نحن", "أقسامنا", "أعمالنا", "تواصل"],
    cta: "لنتحدث",
    hero: {
      eyebrow: "استراتيجية",
      title: "نبدأ من السبب، لا من الطلب — ثم نمشي معك كل خطوة حتى النتيجة.",
      tagline: "نموّك… بنظامنا.",
      primary: "لنتحدث",
      secondary: "كيف نعمل؟",
      stats: [
        { prefix: "+", value: "٤٠", label: "عميل نشط" },
        { value: "٥", label: "أقسام متكاملة" },
        { value: "دبي", label: "مكتب ٥٠١" },
      ],
    },
    about: {
      n: "٠١", eyebrow: "ما الذي يميّزنا",
      titleA: "الشركات العظيمة لا تُبنى بالصدفة…", titleB: "بل بالقرارات الصحيحة.",
      lead: "لا نبيع خدمات.",
      body: "نجد الناقص، ونبنيه. نعمل من داخل الشركة مع فريقك، لا بعيداً عنه، ونصل الأقسام كلها بخيطٍ واحد؛ فلا تتناقض الرسالة، ولا يضيع العميل بين يدٍ ويد.",
    },
    vision: {
      n: "٠٢", eyebrow: "فلسفتنا",
      title: "كل شركةٍ منظومة. وكل منظومةٍ تصنع أنماطاً. وكل نمطٍ يكشف قصة. وكل قصةٍ تبدأ بقرار.",
      body: "نبدأ من حيث لا يُرى العمل… لننتهي عند ما يراه العميل. فكل مرحلةٍ تُجهّز التي بعدها، والترتيب هنا شرطٌ لا تفضيل.",
    },
    method: {
      n: "٠٣", eyebrow: "كيف نعمل",
      kicker: "أربع خطوات، لا اجتهاد.",
      title: "نُشخّص. نُخطّط. ننفّذ. ونقيس.",
      hint: "اضغط أي خطوة لقراءة التفصيل",
      steps: [
        { i: "٠١", t: "نُشخّص", d: "لا نبدأ من الطلب، بل من السبب. نسأل «لماذا» حتى نصل إليه — ثم نبني عليه." },
        { i: "٠٢", t: "نُخطّط", d: "الاستراتيجية قرارٌ مبنيٌّ على ما وجدناه، لا على ما هو شائع." },
        { i: "٠٣", t: "الخطة", d: "لكل خطوةٍ صاحبها وموعدها ومقياس نجاحها." },
        { i: "٠٤", t: "ننفّذ", d: "بأيدينا، وبأقسامنا، من أول خطوةٍ إلى آخرها." },
        { i: "٠٥", t: "نقيس", d: "سجّلنا أرقامك يوم بدأنا، فنعرف ما تحرّك وما لم يتحرّك." },
        { i: "٠٦", t: "نُعدّل", d: "ما أثمر يُوسَّع، وما تعثّر يُعدَّل — بقرارٍ مبنيٍّ على رقم، لا على انطباع." },
      ],
    },
    services: {
      n: "٠٤", eyebrow: "أقسامنا الخمسة",
      title: "لا نعرض قائمةً لتختار منها.",
      lede: "نُشخّص، فنجد الفجوة، ثم نملأها. وإن كان الناقص خارج هذه القائمة… نبنيه.",
      items: [
        { t: "الاستراتيجية والدراسات", d: "دراسة الحالة · دراسة الجدوى · التموضع · حجم السوق · تحليل المنافسين · الخطط" },
        { t: "العمليات", d: "أنظمة التشغيل · توزيع المسؤوليات · الهيكل التنظيمي · الأرشفة والجداول · أدلة العمل" },
        { t: "المبيعات", d: "المسار من الفرصة إلى الإغلاق · إدارة علاقات العملاء · ملفات الفريق وأدواته · تدريب البيع" },
        { t: "التسويق والعلامة", d: "الهوية البصرية ودليل العلامة · المحتوى · التصوير والفيديو · السوشيال ميديا · الحملات" },
        { t: "التقنية والذكاء الاصطناعي", d: "المواقع · المتاجر · التطبيقات · الأنظمة الداخلية · الأتمتة · وكلاء الذكاء الاصطناعي" },
        { t: "المتابعة والقياس", d: "رقمٌ قبل، ورقمٌ بعد. وما بينهما قرارُنا التالي." },
      ],
      featured: { eyebrow: "أساس النجاح", t: "العلامة الشخصية", d: "المؤسس هو الانطباع الأول. نحوّل حضورك إلى أصلٍ تجاري طويل الأمد — يفتح أبواب الشراكات والكفاءات والعملاء الذين تريدهم فعلاً." },
    },
    audience: {
      n: "٠٥", eyebrow: "مع من نعمل",
      title: "ابدأ من الطريق الصحيح.",
      lede: "سواء كنت تُطلق شيئاً جديداً أو تُوسّع شركةً قائمة — نضع الأساس الصحيح من اليوم الأول.",
      a: {
        tag: "الأثر الأكبر",
        t: "إن كنت تبدأ مشروعاً جديداً",
        d: "ابدأ على أرضٍ صلبة قبل أن تتراكم الأخطاء: استراتيجية واضحة، ونظام تشغيل من اليوم الأول، وعلامة شخصية وتجارية، وفريق يعرف إلى أين يتّجه.",
        items: ["دراسة جدوى وخطة عمل مفصّلة", "هيكل تشغيلي وأدلة عمل قبل أول عميل", "علامة تجارية وشخصية متّسقة", "إشراف كامل خلال أول ٦ أشهر"],
      },
      b: {
        t: "إن كنت تدير شركةً قائمة",
        d: "نحلّل ما يعمل وما لا يعمل، ونعيد ترتيب الأولويات، ونبني خطة تطويرٍ على مراحل. نعمل مع واقعك بتفاصيله، لا مع افتراضاتٍ مثالية.",
        items: ["رسم الفجوات في أنظمتك الحالية", "إعادة هيكلة المبيعات والتسويق", "تطوير القيادة والفريق", "خطة نموٍّ مسندة بالأرقام"],
      },
    },
    results: {
      n: "٠٦", eyebrow: "العمل الفعلي",
      title: "ما نُسلّمه فعلاً",
      lede: "في عملنا مع عميلٍ واحد، هذا ما أنجزناه:",
      items: [
        { i: "٠١", t: "بنينا أساس الشركة", d: "بدأنا بفهم الواقع، ثم وضعنا الاستراتيجية، ثم نفّذنا أنظمة عملٍ تبقى بعدنا." },
        { i: "٠٢", t: "خمس مراحل توظيف كاملة", d: "من الوصف الوظيفي إلى العرض النهائي — خطّطنا وأدرنا التوظيف لأكثر من ١٥ دوراً." },
        { i: "٠٣", t: "أتمتة كاملة لإدارة العملاء", d: "ربطنا الأنظمة، وأعددنا HubSpot و Zoho، وأتمتنا المتابعة من أول اجتماع حتى الإغلاق." },
        { i: "٠٤", t: "قرارات مبنية على أرقام", d: "مقارنات موردين، وتحليل مواصفات فنية، ونماذج مالية، ووثائق استثمارية." },
        { i: "٠٥", t: "مسار مبيعات من الصفر", d: "بنينا قنوات البيع وصمّمنا رحلة العميل من أول تواصل حتى التوقيع." },
        { i: "٠٦", t: "هوية وحملات ومحتوى", d: "من الهوية البصرية إلى حملات جوجل وميتا، مع إدارة محتوى شهرية." },
      ],
      close: "وكل هذا… مع شركةٍ واحدة. في وقتٍ واحد.",
    },
    partners: { n: "٠٧", title: "شركاء النجاح", lede: "علاماتٌ وثِقت بنموّها معنا", close: "معك من أول فكرة… إلى أول عميل… إلى أول توسّع." },
    contact: {
      n: "٠٨", title: "ابدأ من هنا.",
      body: "جلسة تشخيصٍ مجانية. نجلس معك، ونفهم شركتك من الداخل، ونخرج بصورةٍ واضحة: أين أنت، وما الذي يعوقك، وما الخطوة التالية. ثم تقرّر أنت.",
      primary: "لنتحدث", secondary: "واتساب ↗",
    },
    footer: { tagline: "نموّك… بنظامنا.", address: "مكتب ٥٠١، دبي، الإمارات", links: "روابط سريعة", touch: "تواصل معنا", rights: "© ٢٠٢٥ استراتيجية. جميع الحقوق محفوظة." },
  },
};
